#!/bin/bash

notify() {
	echo "$*"
	notify-send "Maim OCR" "$*" &
}

take_screenshot() {
	maim --select --hidecursor --format=png --quality 1 | convert png:- -monochrome -alpha off -bordercolor White -border 10x10 png:-
}

tesseract_recognize() {
	tesseract stdin stdout --tessdata-dir "$HOME/.local/share/tessdata" -l "eng"
}

run_ocr() {
	RESULT=$(take_screenshot | tesseract_recognize)
	echo $RESULT
	if [[ -n $RESULT ]]; then
		xclip -selection clipboard <<< "$RESULT"
		notify "Copied $RESULT"
	else
		notify "Failed"
		return 1
	fi
}

main() {
	run_ocr
}

main