#!/bin/sh

for reference in ./*.mkv; do
    to_retime=./subs.ja/$(basename "${reference/.mkv/.srt}")
    retimed=${to_retime%.*}_retimed.${to_retime##*.}
    ffsubsync "$reference" -i "$to_retime" -o "$retimed"
done
