#!/bin/sh

export VISUAL=vim
export EDITOR=vim

sxhkd &

bspc monitor DP-2-2 -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#2e2e2e"
bspc config normal_border_color "#000000"

bspc rule -a Chromium desktop='^3' border=off follow=on
bspc rule -a firefox desktop='^3' border=off follow=on
bspc rule -a discord desktop='^2' border=off
bspc rule -a TelegramDesktop desktop='^1' border=off
bspc rule -a Zathura border=off state=tiled
bspc rule -a Spotify desktop='^7' border=off state=tiled follow=on
bspc rule -a kitty:float state=floating
bspc rule -a Pavucontrol state=floating rectangle=570x400+675+340

# Keyboard
fcitx &

# Audio
start-pulseaudio-x11

# Notifications
dunst &

# Cursor
xsetroot -cursor_name left_ptr

# Compositor and Wallpaper
feh --bg-fill $HOME/Pictures/wallpapers/t440p-exploded.png

$HOME/.config/feh-blur/feh-blur -s

$HOME/.config/feh-blur/feh-blur -d -b 8

picom --backend glx &

# Bar
$HOME/.config/polybar/launch.sh
bspc config top_padding 28
