#!/bin/sh

export VISUAL=vim
export EDITOR=vim
# export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"

setxkbmap -option compose:menu

sxhkd &i

# TODO: Move this conditional statement to a separate file
if [[ $(xrandr -q | grep "DVI-D-0 connected") ]]; then
  xrandr --output HDMI-A-0 --primary --mode 1920x1080 --output DVI-D-0 --mode 1920x1080 --left-of HDMI-A-0
fi

# TODO: Add multimonitor support
# bspc monitor HDMI-1 -d 一 二 三 四 五 六 七 八 九 十

bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#2e2e2e"
bspc config normal_border_color "#000000"
bspc config border_width 0

# If refreshing bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

bspc rule -a Chromium desktop='3' border=off follow=on
# bspc rule -a Brave-browser desktop='3' border=off follow=on
bspc rule -a firefox:Devtools state=floating center=true
bspc rule -a discord desktop='2' border=off
bspc rule -a TelegramDesktop desktop='1' border=off
bspc rule -a Zathura border=off state=tiled
bspc rule -a Spotify desktop='7' border=off state=tiled follow=on
bspc rule -a kitty:float state=floating
bspc rule -a Pavucontrol state=floating rectangle=570x400+675+340 center=true

# Keyboard
fcitx &

# Audio
start-pulseaudio-x11

# Notifications
dunst &

# Cursor
xsetroot -cursor_name left_ptr

# Compositor and Wallpaper
feh --bg-fill $HOME/Pictures/wallpaper

# $HOME/.config/feh-blur/feh-blur -s

# $HOME/.config/feh-blur/feh-blur -d -b 8

picom --backend glx &

# Bar
$HOME/.config/polybar/launch.sh
bspc config -m HDMI-A-0 bottom_padding 28
